from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('',
    url(r'^$', 'groupsite.views.home'),
    url(r'^people/$', 'groupsite.views.people'),
    url(r'^people/(\d+)/$', 'groupsite.views.people_view'),
    url(r'^newspaper/$', 'groupsite.views.newspaper'),
    url(r'^news/$', 'groupsite.views.news'),
    url(r'^news/(\d+)/$', 'groupsite.views.news_view'),
    url(r'^science/$', 'groupsite.views.science'),
    url(r'^science/(\d+)/$', 'groupsite.views.science_view'),
    url(r'^publications/$', 'groupsite.views.publications'),
    url(r'^blog/$', 'groupsite.views.blog'),
    url(r'^posts/$', 'groupsite.views.posts'),
    url(r'^posts/(\d+)/$', 'groupsite.views.post_view'),
    url(r'^restricted/edit/$', 'groupsite.views.edit_profile'),
    url(r'^restricted/networking/$', 'groupsite.views.edit_network'),
    url(r'^restricted/configs/$', 'groupsite.views.edit_configs'),
    url(r'^restricted/create_news/$', 'groupsite.views.create_news'),
    url(r'^restricted/create_post/$', 'groupsite.views.create_post'),
    url(r'^restricted/create_video/$', 'groupsite.views.create_video'),
    url(r'^restricted/create_image/$', 'groupsite.views.create_image'),
    url(r'^restricted/editor/$', 'groupsite.views.editor_view'),
    url(r'^restricted/authorize_post/(\d+)/$', 'groupsite.views.auth_post'),
    url(r'^restricted/deny_post/(\d+)/$', 'groupsite.views.deny_post'),
    url(r'^restricted/authorize_news/(.*)/$', 'groupsite.views.auth_news'),
    url(r'^restricted/deny_news/(\d+)/$', 'groupsite.views.deny_news'),
    url(r'^restricted/authorize_science/(\d+)/$', 'groupsite.views.auth_science'),
    url(r'^restricted/deny_science/(\d+)/$', 'groupsite.views.deny_science'),
    url(r'^restricted/upload_publication/$', 'groupsite.views.upload_publication'),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name' : 'gmaologin.html'}),
    url(r'^logout/$', 'django.contrib.auth.views.logout_then_login', {'login_url' : '/gmao/login/'}),    
    )
